# Site settings
baseurl: http://www.math-phys.science

# Build settings
permalink: pretty
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: [ "superscript",
  				"fenced_code_blocks",
                "hard_wrap",
                "autolink",
                "tables",
                "strikethrough",
                "with_toc_data",
                "highlight",
                "prettify",
                "no_intra_emphasis" ]
  # DON'T USE"superscript", never use this with Mathjax,this will cause bug
safe: false
#pygments: false
excerpt_separator: "\n\n\n"
#paginate: 5