# Site settings
baseurl: http://www.math-phys.science

# Build settings
permalink: pretty
markdown: redcarpet
highlighter: pygments
#pygments: false
redcarpet:
  extensions: [ "fenced_code_blocks",
				"hard_wrap",
				"autolink",
				"prettify",
				"highlight",
				"strikethrough",
				"no_intra_emphasis",
				"tables" ]
  # DON'T USE"superscript", "with_toc_data", never use them with Mathjax, it will cause bug
safe: false

excerpt_separator: "\n\n\n"
#paginate: 5