# Site settings
baseurl: http://www.math-phys.science

# Build settings
permalink: pretty
markdown: redcarpet
highlighter: pygments

safe: false
#pygments: false
excerpt_separator: "\n\n\n"
#paginate: 5